Theme: minima
title: capitães do mangue
author: Ulsac
email: Ulsac@prontonmail.com
description: > # this means to ignore newlines until "baseurl:"
 Belford Roxo, city of love? seems more like baixada´s Pandora´s box

# social links
twitter_username: luccas004 # DO NOT include the @ character, or else the build will fail!
github_username: Ulsac  # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
